### ISSUE TITLE
第96页关于NSPopover的问题

### ISSUE THREAD

**Issue by qixizhu** [javaliker/MacDevEbookIssues#1]
1.初始化：shareViewController 和 feedBackViewController 也需要初始化，不知道需不需要加上。代码如下：
- (ShareViewController *)shareViewController {
  if (!_shareViewController) {
      _shareViewController = [[ShareViewController alloc] initWithNibName:@"ShareViewController" bundle:nil];
  }
  return _shareViewController;
  }
- (FeedbackViewController *)feedBackViewController {
  if (!_feedBackViewController) {
      _feedBackViewController = [[FeedbackViewController alloc] initWithNibName:@"FeedbackViewController" bundle:nil];
  }
  return _feedBackViewController;
  }
  2.按钮点击事件：
  showRelativeToRect:ofView:preferredEdge: 方法中 preferredEdge 的参数类型是 NSRectEdge。代码如下：
- (IBAction)sharePopover:(NSButton *)sender {
  // 显示在 button 下面
  [self.sharePopover showRelativeToRect:[sender bounds] ofView:sender preferredEdge:NSRectEdgeMaxY];
  }
- (IBAction)feedBackPopover:(NSButton *)sender {
  // 显示在 button 上面
  [self.feedBackPopover showRelativeToRect:[sender bounds] ofView:sender preferredEdge:NSRectEdgeMinY];
  }
  tip:我自己试了下，如果使用 CGRectMaxYEdge 和 CGRectMinYEdge 点击效果也是正确，但是 Xcode 会报警告。

**Comment by javaliker** [comment]
初始化的代码是需要的，告警的问题已经修改。
