### ISSUE TITLE
关于storyboard版本 与 文字字号

### ISSUE THREAD

**Issue by ForkPanda** [javaliker/MacDevEbookIssues#2]
刚刚购买，目前看了几分钟，发现的几个问题提一下
1.目前我们会更倾向于使用 storyboard + autolayout 布局，你这本书的例子是不是应该换一下？毕竟看书的不是做企业级工程，我们更希望能用到最新的东西。
2.文字字号过大，导致代码的可读性非常不好。如果调整字号，会将下一页的图片加到当前页面，结果是图文对照不方便。希望可以在下个版本修复，感谢。

**Comment by javaliker** [comment]
我这边手写代码 和xib较多。  不过都差不多吧  你会了一种 其它的都很容易自己转换。 不太喜欢用storyboard的地方在于页面少了还凑合，多了线连接起来感觉有些乱  有时候文件打开也比较慢。  。字号问题可以放小一个字号。看看效果 。我弄好了提前给你看看  你留个邮箱吧。

**Comment by ForkPanda** [comment]
151266405@qq.com
我用的是 ibook 看的 epub，缩小了字号之后，排版会自动调整，但是调整之后就会很蛋疼，因为可能图在这一页，文字在下一页。还有就是代码段，目前来看代码段比较难以阅读，需要拷贝出来才能看，在书上直接看会有点难以阅读。

**Comment by javaliker** [comment]
@ForkPanda     ibook 的阅读问题 暂时不好解决 因为是使用gitbook工具生成的，格式怎么弄能对ibook支持的更好一些 目前还不知道怎么弄。 建议电脑上尽量阅读PDF吧

**Comment by javaliker** [comment]
已经沟通
