### ISSUE TITLE
部分有笔误？

### ISSUE THREAD

**Issue by acche** [javaliker/MacDevEbookIssues#5]
定位到: 滚动到指定位置章节代码:

![image](https://cloud.githubusercontent.com/assets/1592763/16940389/1f023062-4dbc-11e6-881d-ea30a0e1b7ba.png)
![image](https://cloud.githubusercontent.com/assets/1592763/16940398/2ccbda40-4dbc-11e6-9f95-1053e82c651a.png)
两处地方 多了一个点。

**Comment by acche** [comment]
定位到: UI属性说明
![image](https://cloud.githubusercontent.com/assets/1592763/16941165/05aa5e46-4dc1-11e6-9c95-464444d9e63b.png)
多了个“的”

**Comment by javaliker** [comment]
谢谢支持  下一版本修正
