### ISSUE TITLE
macOSwift版，有OC版代码 - 【两个视图控制之间切换方法】

### ISSUE THREAD

**Issue by jiangchaoyy** [javaliker/MacDevEbookIssues#8]
macOSwift版：
第九章 视图控制器
两个视图控制器之间切换方法
2. Sheet方式
此处代码为OC版
- (IBAction)presentAsSheetAction:(id)sender {
   PresentViewController *p = [[PresentViewController alloc]init];
   [self presentViewControllerAsSheet:p];
  }

**Comment by javaliker** [comment]
已经修改 下一个版本发布  谢谢！
